name: Npm Publish

on:
  push:
    branches:
      - f_action

jobs:
  publish-npm:
    if: "contains(github.event.head_commit.message, 'release')"
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.6

      - name: Setup Chomp
        uses: guybedford/chomp-action@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Run build Provider
        working-directory: ./packages/dancf-provider
        run: chomp build

      # - name: Publish to NPM
      #   run: pnpm -r publish --access public --no-git-checks --publish-branch main --filter ./packages
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.PUBLISH_NPM_TOKEN}}
